---
- name: Deploy Apache Docker Container using Ansible
  hosts: all
  become: true
  
  tasks:
    - name: Configure Docker Repository
      yum_repository:
        name: Docker
        description: "Docker Repo"
        baseurl: "https://download.docker.com/linux/centos/docker-ce.repo"
        gpgcheck: no
      when: ansible_os_family == "RedHat"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Starting Docker Daemon
      service:
        name: docker
        state: started
      when: ansible_os_family == "Debian"

    - name: Install pip3
      yum:
        name: python3-pip
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
      become: true
      when: ansible_os_family == "Debian"

    - name: Install Docker SDK for Python
      pip:
        name: docker
      become: true

    - name: Pull Apache Docker Image
      docker_image:
        name: httpd
        tag: latest
        source: pull
      register: z

    - name: Creating a Persistence Volume Directory
      file:
        path: "/home/Targetnode/httpd"
        state: directory

    - name: Copy index.html to host directory
      copy:
        src: "/home/Mainnode/Networkingassignment/index.html"
        dest: "/home/Targetnode/httpd/index.html"

    - name: Configure Networking for Apache Container
      docker_network:
        name: apache_network
        driver: bridge
        ipam_config:
          - subnet: "172.168.10.0/30"

    - name: Run Apache Docker Container
      docker_container:
        name: apache-httpd
        image: httpd
        state: started
        restart_policy: always
        exposed_ports:
          - "80"
        ports:
          - "8888:80"
        volumes:
          - "/home/Targetnode/httpd:/usr/local/apache2/htdocs"
        networks:
          - name: apache_network

